export const obj = [
    {
        SummerCollection: [
            {
                id: "p_01",
                name: "Product Name",
                collectionType: "Summer Collection",
                price: "Rs. 1000",
                image: "https://zellbury.com/media/catalog/product/cache/a8a5e6dd860d201a9e47af940dffc15b/z/m/zmh19002-red_2_1.jpg",
                description: "A product description is the marketing copy used to describe a product's value proposition to potential customers. A compelling product description provides.",
            },
            {
                id: "p_02",
                name: "Product Name",
                collectionType: "Summer Collection",
                price: "Rs. 1000",
                image: "https://zellbury.com/media/catalog/product/cache/a8a5e6dd860d201a9e47af940dffc15b/z/m/zmhj19026-black_1.jpg",
                description: "Lor e m Lorem LoremLor emLore mLor emLo rem",
            },
            {
                id: "p_03",
                name: "Product Name",
                collectionType: "Summer Collection",
                price: "Rs. 1000",
                image: "https://zellbury.com/media/catalog/product/cache/a8a5e6dd860d201a9e47af940dffc15b/z/m/zmjp19001-navy-white_2_2.jpg",
                description: "Lor e m Lorem LoremLor emLore mLor emLo rem",
            },
            {
                id: "p_04",
                name: "Product Name",
                collectionType: "Summer Collection",
                price: "Rs. 1000",
                image: "https://zellbury.com/media/catalog/product/cache/a8a5e6dd860d201a9e47af940dffc15b/z/m/zmk19093-e-yellow_1_6.jpg",
                description: "Lor e m Lorem LoremLor emLore mLor emLo rem",
            },
            {
                id: "p_05",
                name: "Product Name",
                collectionType: "Summer Collection",
                price: "Rs. 1000",
                image: "https://zellbury.com/media/catalog/product/cache/a8a5e6dd860d201a9e47af940dffc15b/z/m/zmh19002-red_2_1.jpg",
                description: "Lor e m Lorem LoremLor emLore mLor emLo rem",
            },
            {
                id: "p_06",
                name: "Product Name",
                collectionType: "Summer Collection",
                price: "Rs. 1000",
                image: "https://zellbury.com/media/catalog/product/cache/a8a5e6dd860d201a9e47af940dffc15b/z/m/zmhj19026-black_1.jpg",
                description: "Lor e m Lorem LoremLor emLore mLor emLo rem",
            },
            {
                id: "p_07",
                name: "Product Name",
                collectionType: "Summer Collection",
                price: "Rs. 1000",
                image: "https://zellbury.com/media/catalog/product/cache/a8a5e6dd860d201a9e47af940dffc15b/z/m/zmjp19001-navy-white_2_2.jpg",
                description: "Lor e m Lorem LoremLor emLore mLor emLo rem",
            },
            {
                id: "p_08",
                name: "Product Name",
                collectionType: "Summer Collection",
                price: "Rs. 1000",
                image: "https://zellbury.com/media/catalog/product/cache/a8a5e6dd860d201a9e47af940dffc15b/z/m/zmk19093-e-yellow_1_6.jpg",
                description: "Lor e m Lorem LoremLor emLore mLor emLo rem",
            },
            {
                id: "p_09",
                name: "Product Name",
                collectionType: "Summer Collection",
                price: "Rs. 1000",
                image: "https://zellbury.com/media/catalog/product/cache/a8a5e6dd860d201a9e47af940dffc15b/z/m/zmh19002-red_2_1.jpg",
                description: "Lor e m Lorem LoremLor emLore mLor emLo rem",
            },
            {
                id: "p_10",
                name: "Product Name",
                collectionType: "Summer Collection",
                price: "Rs. 1000",
                image: "https://zellbury.com/media/catalog/product/cache/a8a5e6dd860d201a9e47af940dffc15b/z/m/zmhj19026-black_1.jpg",
                description: "Lor e m Lorem LoremLor emLore mLor emLo rem",
            },
            {
                id: "p_11",
                name: "Product Name",
                collectionType: "Summer Collection",
                price: "Rs. 1000",
                image: "https://zellbury.com/media/catalog/product/cache/a8a5e6dd860d201a9e47af940dffc15b/z/m/zmjp19001-navy-white_2_2.jpg",
                description: "Lor e m Lorem LoremLor emLore mLor emLo rem",
            },
            {
                id: "p_12",
                name: "Product Name",
                collectionType: "Summer Collection",
                price: "Rs. 1000",
                image: "https://zellbury.com/media/catalog/product/cache/a8a5e6dd860d201a9e47af940dffc15b/z/m/zmk19093-e-yellow_1_6.jpg",
                description: "Lor e m Lorem LoremLor emLore mLor emLo rem",
            },
        ],
        WinterCollection: [
            {
                id: "p_01",
                name: "Product Name",
                collectionType: "Winter Collection",
                price: "Rs. 1000",
                image: "https://assets.adidas.com/images/w_383,h_383,f_auto,q_auto:sensitive,fl_lossy/7d3d84d8dc7945c49a96ac8500370742_9366/adidas-essentials-small-logo-hoodie.jpg",
                description: "Lor e m Lorem LoremLor emLore mLor emLo rem",
            },
            {
                id: "p_02",
                name: "Product Name",
                collectionType: "Winter Collection",
                price: "Rs. 1000",
                image: "https://assets.adidas.com/images/w_383,h_383,f_auto,q_auto:sensitive,fl_lossy/f41f1aa80c5840468b09aca10115ed87_9366/tiro-21-sweat-hoodie.jpg",
                description: "Lor e m Lorem LoremLor emLore mLor emLo rem",
            },
            {
                id: "p_03",
                name: "Product Name",
                collectionType: "Winter Collection",
                price: "Rs. 1000",
                image: "https://assets.adidas.com/images/w_383,h_383,f_auto,q_auto:sensitive,fl_lossy/f41f1aa80c5840468b09aca10115ed87_9366/tiro-21-sweat-hoodie.jpg",
                description: "Lor e m Lorem LoremLor emLore mLor emLo rem",
            },
            {
                id: "p_04",
                name: "Product Name",
                collectionType: "Winter Collection",
                price: "Rs. 1000",
                image: "https://assets.adidas.com/images/w_383,h_383,f_auto,q_auto:sensitive,fl_lossy/9d9baf98f6a045c088f0ac8a012f4ea7_9366/trefoil-hoodie.jpg",
                description: "Lor e m Lorem LoremLor emLore mLor emLo rem",
            },
            {
                id: "p_05",
                name: "Product Name",
                collectionType: "Winter Collection",
                price: "Rs. 1000",
                image: "https://assets.adidas.com/images/w_383,h_383,f_auto,q_auto:sensitive,fl_lossy/9d9baf98f6a045c088f0ac8a012f4ea7_9366/trefoil-hoodie.jpg",
                description: "Lor e m Lorem LoremLor emLore mLor emLo rem",
            },
            {
                id: "p_06",
                name: "Product Name",
                collectionType: "Winter Collection",
                price: "Rs. 1000",
                image: "https://assets.adidas.com/images/w_383,h_383,f_auto,q_auto:sensitive,fl_lossy/7d3d84d8dc7945c49a96ac8500370742_9366/adidas-essentials-small-logo-hoodie.jpg",
                description: "Lor e m Lorem LoremLor emLore mLor emLo rem",
            },
            {
                id: "p_07",
                name: "Product Name",
                collectionType: "Winter Collection",
                price: "Rs. 1000",
                image: "https://assets.adidas.com/images/w_383,h_383,f_auto,q_auto:sensitive,fl_lossy/f41f1aa80c5840468b09aca10115ed87_9366/tiro-21-sweat-hoodie.jpg",
                description: "Lor e m Lorem LoremLor emLore mLor emLo rem",
            },
            {
                id: "p_08",
                name: "Product Name",
                collectionType: "Winter Collection",
                price: "Rs. 1000",
                image: "https://assets.adidas.com/images/w_383,h_383,f_auto,q_auto:sensitive,fl_lossy/f41f1aa80c5840468b09aca10115ed87_9366/tiro-21-sweat-hoodie.jpg",
                description: "Lor e m Lorem LoremLor emLore mLor emLo rem",
            },
            {
                id: "p_09",
                name: "Product Name",
                collectionType: "Winter Collection",
                price: "Rs. 1000",
                image: "https://assets.adidas.com/images/w_383,h_383,f_auto,q_auto:sensitive,fl_lossy/f41f1aa80c5840468b09aca10115ed87_9366/tiro-21-sweat-hoodie.jpg",
                description: "Lor e m Lorem LoremLor emLore mLor emLo rem",
            },
            {
                id: "p_10",
                name: "Product Name",
                collectionType: "Winter Collection",
                price: "Rs. 1000",
                image: "https://assets.adidas.com/images/w_383,h_383,f_auto,q_auto:sensitive,fl_lossy/7d3d84d8dc7945c49a96ac8500370742_9366/adidas-essentials-small-logo-hoodie.jpg",
                description: "Lor e m Lorem LoremLor emLore mLor emLo rem",
            },
            {
                id: "p_11",
                name: "Product Name",
                collectionType: "Winter Collection",
                price: "Rs. 1000",
                image: "https://assets.adidas.com/images/w_383,h_383,f_auto,q_auto:sensitive,fl_lossy/7d3d84d8dc7945c49a96ac8500370742_9366/adidas-essentials-small-logo-hoodie.jpg",
                description: "Lor e m Lorem LoremLor emLore mLor emLo rem",
            },
            {
                id: "p_12",
                name: "Product Name",
                collectionType: "Winter Collection",
                price: "Rs. 1000",
                image: "https://assets.adidas.com/images/w_383,h_383,f_auto,q_auto:sensitive,fl_lossy/7d3d84d8dc7945c49a96ac8500370742_9366/adidas-essentials-small-logo-hoodie.jpg",
                description: "Lor e m Lorem LoremLor emLore mLor emLo rem",
            },
        ],
    }
]